# Generated by Django 4.0.3 on 2022-05-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_is_regular_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_since',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
