# Generated by Django 4.0.3 on 2022-05-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_user_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_picture',
            field=models.BinaryField(null=True),
        ),
    ]
