# Generated by Django 4.0.3 on 2022-05-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_user_profile_pic'),
        ('members', '0011_user_description_alter_user_profile_pic'),
    ]

    operations = [
    ]
