# Generated by Django 4.0.3 on 2022-05-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_merge_20220513_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
