# Generated by Django 4.0.3 on 2022-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField()),
                ('entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
