# Generated by Django 4.0.3 on 2022-04-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Movie Name'),
        ),
    ]
