# Generated by Django 4.0.3 on 2022-04-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_movies_delete_movielistentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
