# Generated by Django 4.0.3 on 2022-04-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
