# Generated by Django 4.0.3 on 2022-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_comments_tittle_comments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Ai_FeedBack',
            field=models.IntegerField(null=True, verbose_name='AiFeedBack'),
        ),
        migrations.AddField(
            model_name='comments',
            name='Ai_Probability_FeedBack',
            field=models.FloatField(null=True, verbose_name='AiProbabilityFeedBack'),
        ),
    ]
