# Generated by Django 4.0.3 on 2022-05-07 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='critic_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criticname', to=settings.AUTH_USER_MODEL),
        ),
    ]
