# Generated by Django 4.0.3 on 2022-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comments_critic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='critic_name',
        ),
        migrations.AddField(
            model_name='comments',
            name='critic_username',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Critic_Name'),
        ),
    ]
