# Generated by Django 4.0.3 on 2022-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_comments_critic_name_comments_critic_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='movie_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Movie_Name'),
        ),
    ]
