# Generated by Django 4.0.3 on 2022-05-12 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_list',
            field=models.ManyToManyField(related_name='watch_list_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
