# Generated by Django 4.0.3 on 2022-05-13 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0019_movie_watch_list_remove_movie_likes_movie_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='seen',
            field=models.ManyToManyField(related_name='seen_movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserLikeMovie',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
