# Generated by Django 4.0.3 on 2022-05-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_watchlist_movie_remove_watchlist_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Movie Gender')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='gender',
            field=models.ManyToManyField(related_name='genders', to='home.gendermovies'),
        ),
    ]
