# Generated by Django 4.0.3 on 2022-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_gendermovies_movie_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_top_250',
            field=models.BooleanField(default=False),
        ),
    ]
